### PR TITLE
fix: #147 Set `purgeOnStart: true` to process multiple sites as a server

### LINKED ISSUE #147: Does gpt-crawler server always return same site?
I am trying `gpt-crawler` in server mode, but after the first response, the same responses are always returned.
Is there a problem with my configuration or request?

# config and server command

```typescript
import { Config } from "./src/config";

export const defaultConfig: Config = {
  url: "https://google.com",
  match: "**",
  maxPagesToCrawl: 1,
  selector: "html",
  outputFileName: "output.json",
  maxTokens: 100000,
};
```

```
npm run start:server
```

# request

```bash
$ cat tmp/crawl_example.json
{
  "url": "https://example.com/",
  "match": "https://example.com/**",
  "outputFileName": "output_example.json",
  "maxPagesToCrawl": 1,
  "maxTokens": 2000
}

$ curl -XPOST http://localhost:3000/crawl  -H "Content-Type: application/json" -d@tmp/crawl_example.json
[
  {
    "title": "Example Domain",
    "url": "https://example.com/",
    "html": "Example Domain\n\nThis domain is for use in illustrative examples in documents. You may use this domain in literature without prior coordination or asking for permission.\n\nMore information..."
  }
]%

# First request is LGTM

$ cat tmp/crawl_wikipedia.json
{
  "url": "https://wikipedia.org/",
  "match": "https://wikipedia.org/**",
  "outputFileName": "output_wikipedia.json",
  "maxPagesToCrawl": 1,
  "maxTokens": 2000
}

$ curl -XPOST http://localhost:3000/crawl  -H "Content-Type: application/json" -d@tmp/crawl_wikipedia.json
[
  {
    "title": "Example Domain",
    "url": "https://example.com/",
    "html": "Example Domain\n\nThis domain is for use in illustrative examples in documents. You may use this domain in literature without prior coordination or asking for permission.\n\nMore information..."
  }
]%

# Second request is same as first one.
```

### PR DESCRIPTION
**Pull request by kaibadash**
Fix #147 Set `purgeOnStart: true` to process multiple sites as a server.

### CODE REVIEW

File: src/core.ts [hunk 1]
```diff
@@ -54,83 +54,89 @@ export async function crawl(config: Config) {
...
+            );
+            log.info(
+              `Aborting requests for as this is a resource excluded route`,
+            );
+          },
+        ],
+      },
+      new Configuration({
+        purgeOnStart: true,
+      }),
```
Comment (kaibadash) [inline src/core.ts:138]: I added a configuration. Other differences are due to lint.

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,14 +1,12 @@
 # [1.4.0](https://github.com/BuilderIO/gpt-crawler/compare/v1.3.0...v1.4.0) (2024-01-15)
 
-
 ### Bug Fixes
 
-* linting ([0f4e58b](https://github.com/BuilderIO/gpt-crawler/commit/0f4e58b400eab312e7b595d7a2472bae93055415))
-
+- linting ([0f4e58b](https://github.com/BuilderIO/gpt-crawler/commit/0f4e58b400eab312e7b595d7a2472bae93055415))
```
Comment (kaibadash) [inline CHANGELOG.md:5]: ?

Comment (marcelovicentegc) [reply CHANGELOG.md:5]: It occurs to me that it might be due to some local configuration on your machine, @kaibadash. The linter is not  configured to look at markdown files.

**Review by marcelovicentegc — APPROVED** [review]
